name: Build DEB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Theos
        uses: Randomblock1/theos-action@v1
        with:
          project-dir: VietMapAutoContinue
          use-rootless: false

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: |
            VietMapAutoContinue/packages/*.deb
